#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="restaurant")]
	public partial class LaporanGrafikPenjualanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LaporanGrafikPenjualanDataContext() : 
				base(global::Restaurant.Properties.Settings.Default.restaurantConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LaporanGrafikPenjualanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaporanGrafikPenjualanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaporanGrafikPenjualanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaporanGrafikPenjualanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LaporanGrafikPendapatan> LaporanGrafikPendapatans
		{
			get
			{
				return this.GetTable<LaporanGrafikPendapatan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LaporanGrafikPendapatan")]
	public partial class LaporanGrafikPendapatan
	{
		
		private System.Nullable<int> _Tahun;
		
		private System.Nullable<long> _Pendapatan;
		
		public LaporanGrafikPendapatan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tahun", DbType="Int")]
		public System.Nullable<int> Tahun
		{
			get
			{
				return this._Tahun;
			}
			set
			{
				if ((this._Tahun != value))
				{
					this._Tahun = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pendapatan", DbType="BigInt")]
		public System.Nullable<long> Pendapatan
		{
			get
			{
				return this._Pendapatan;
			}
			set
			{
				if ((this._Pendapatan != value))
				{
					this._Pendapatan = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
